SELECT 
HOUR(DATETIME) AS 'HOUR',
COUNT(DATETIME) AS 'COUNT'
FROM ANIMAL_OUTS
# WHERE HOUR(DATETIME)>=9 AND HOUR(DATETIME)<=19
#GROUP BY HOUR HAVING HOUR>=9 AND HOUR<=19
ORDER BY HOUR

#AS로 설정한 속성 이름을 시작으로 GROUPING할 수 있다.
# SELECT를 통해 나온 결과로 GROUPING이나 ORDERING을 진행한다. WHERE을 안된다.


#https://velog.io/@kimmjieun/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%9E%85%EC%96%91-%EC%8B%9C%EA%B0%81-%EA%B5%AC%ED%95%98%EA%B8%B01