SELECT car_id,
       ROUND(AVG(DATEDIFF(end_date, start_date) + 1), 1) AS 'AVERAGE_DURATION'
FROM   car_rental_company_rental_history
GROUP  BY car_id
HAVING AVG(DATEDIFF(end_date, start_date) + 1) >= 7
# GROUPING후 나온 대여기간들을 가지고 평균을 내야된다. 
ORDER  BY average_duration DESC,
          car_id DESC 

/*
SELECT *, DATEDIFF(END_DATE,START_DATE) AS 'AVERAGE_DURATION'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
*/

/*
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)),1) AS 'AVERAGE_DURATION'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE DATEDIFF(END_DATE,START_DATE) >= 7
GROUP BY CAR_ID
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
*/