SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE,'%Y-%m-%d') AS 'PUBLISHED_DATE' # y m d 의 순서를 바꿔서는 안된다.
FROM BOOK INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY IN ('경제')
ORDER BY PUBLISHED_DATE ASC

/*
SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%d-%m') AS 'PUBLISHED_DATE'
FROM BOOK INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY IN ('경제')
ORDER BY PUBLISHED_DATE ASC
*/