SELECT PT_NAME, PT_NO, GEND_CD, AGE, 
IF(TLNO IS NULL,'NONE',TLNO)
/*
CASE
    WHEN TLNO IS NULL THEN 'NONE'
    ELSE TLNO
END AS TLNO
*/AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC,PT_NAME ASC

#조건이 간단할 때는 IF 복잡하면 CASE를 쓰도록 하자.