WITH SUB_HISTORY AS
(
    SELECT 
        *, 
        COUNT(*) AS 'RECORDS'
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        DATE_FORMAT(START_DATE,'%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY 
        CAR_ID
)

SELECT 
    MONTH(HISTORY.START_DATE) AS MONTH,
    HISTORY.CAR_ID,
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    INNER JOIN
    SUB_HISTORY
    ON 
        HISTORY.CAR_ID = SUB_HISTORY.CAR_ID
 WHERE 
    SUB_HISTORY.RECORDS >= 5 
    AND DATE_FORMAT(HISTORY.START_DATE,'%Y-%m') BETWEEN '2022-08' AND '2022-10'
 GROUP BY
    HISTORY.CAR_ID,
    MONTH(HISTORY.START_DATE)
 ORDER BY
    MONTH(HISTORY.START_DATE) ASC,
    HISTORY.CAR_ID DESC
    
    
/*
SELECT 
    MONTH(HISTORY.START_DATE) AS MONTH,
    HISTORY.CAR_ID,
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    INNER JOIN
    (
        SELECT *, COUNT(*) AS 'RECORDS'
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE 
            DATE_FORMAT(START_DATE,'%Y-%m') BETWEEN '2022-08' AND '2022-10'
        GROUP BY 
            CAR_ID
    ) SUB_HISTORY
    ON 
        HISTORY.CAR_ID = SUB_HISTORY.CAR_ID
 WHERE 
    SUB_HISTORY.RECORDS >= 5 AND DATE_FORMAT(HISTORY.START_DATE,'%Y-%m') BETWEEN '2022-08' AND '2022-10' # HIS와 SUB_HIS를 INNER한 테이블에는 설정 제외한 날짜가 들어간다.
 GROUP BY
    HISTORY.CAR_ID,
    MONTH(HISTORY.START_DATE)
 ORDER BY
    MONTH(HISTORY.START_DATE) ASC,
    HISTORY.CAR_ID DESC
*/