SELECT DISTINCT CAR.CAR_ID
FROM 
    CAR_RENTAL_COMPANY_CAR AS CAR
    INNER JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RENTAL
    ON CAR.CAR_ID = RENTAL.CAR_ID
WHERE CAR.CAR_TYPE = '세단' AND MONTH(RENTAL.START_DATE) = 10
ORDER BY CAR.CAR_ID DESC