WITH R1 AS(
    SELECT
        *
    FROM
        USED_GOODS_BOARD AS BOARD
        INNER JOIN
        USED_GOODS_USER AS USERS
            ON BOARD.WRITER_ID = USERS.USER_ID
    GROUP BY
        USER_ID
            HAVING COUNT(USER_ID) >= 3
    ORDER BY
        USER_ID DESC
)

SELECT
    USER_ID
    ,NICKNAME
    ,CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소'
    ,CONCAT(SUBSTR(TLNO,1,3), '-',SUBSTR(TLNO,4,4), '-',SUBSTR(TLNO,8,4)) AS '전화번호'
FROM
    R1

#https://blog.edit.kr/entry/mysql-%EB%AC%B8%EC%9E%90%EC%97%B4-%ED%95%A9%EC%B9%98%EA%B8%B0