WITH R1 AS(
    SELECT 
        BOARD.*
        ,USERS.NICKNAME
        ,SUM(PRICE) AS 'TOTAL_SALES'
    FROM
        USED_GOODS_BOARD AS BOARD
        INNER JOIN 
        USED_GOODS_USER AS USERS
            ON BOARD.WRITER_ID = USERS.USER_ID
            AND BOARD.STATUS = 'DONE'
    GROUP BY
        WRITER_ID
)

SELECT 
    WRITER_ID AS 'USER_ID'
    ,NICKNAME
    ,TOTAL_SALES
FROM
    R1
WHERE
    TOTAL_SALES >= 700000
ORDER BY
    TOTAL_SALES ASC