WITH R1 AS(
    SELECT
        PRODUCT_ID
        ,SUM(AMOUNT) AS 'AMOUNT'
        ,PRODUCE_DATE
    FROM
        FOOD_ORDER
    WHERE 
        PRODUCE_DATE LIKE '2022-05%'
    GROUP BY
        PRODUCT_ID
),
R2 AS(
    SELECT
         R1.PRODUCT_ID AS 'PRODUCT_ID' # FOOD_PRODUCT.PRODUCT_ID : R1을 안씀.
        ,PRODUCT_NAME
        ,AMOUNT * PRICE AS 'TOTAL_SALES'
    FROM   
        FOOD_PRODUCT INNER JOIN R1
            ON FOOD_PRODUCT.PRODUCT_ID = R1.PRODUCT_ID
)

SELECT
    *
FROM
    R2
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID ASC