WITH INFO AS
(
    SELECT
        USER_INFO.* 
        ,ONLINE_SALE.ONLINE_SALE_ID	
        ,ONLINE_SALE.PRODUCT_ID	
        ,ONLINE_SALE.SALES_AMOUNT	
        ,ONLINE_SALE.SALES_DATE
    FROM
        USER_INFO
        INNER JOIN
        ONLINE_SALE
            ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
    WHERE USER_INFO.GENDER IS NOT NULL
)

/*
SELECT
    *
FROM
    INFO
*/

SELECT 
    YEAR(SALES_DATE) AS 'YEAR'
    ,MONTH(SALES_DATE) AS 'MONTH'
    ,GENDER AS 'GENDER'
    ,COUNT(DISTINCT USER_ID) AS 'USERS'
FROM
    INFO
GROUP BY 
    YEAR(SALES_DATE) , MONTH(SALES_DATE) , GENDER
ORDER BY
    YEAR ASC, MONTH ASC, GENDER ASC
