WITH R1 AS (
        SELECT 
            BOOK.* , AUTHOR.AUTHOR_NAME
        FROM
            BOOK
            INNER JOIN
            AUTHOR 
                ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
),
R2 AS (
        SELECT 
            R1.* , BOOK_SALES.SALES , BOOK_SALES.SALES_DATE
        FROM
            R1
            INNER JOIN
            BOOK_SALES  
                ON R1.BOOK_ID = BOOK_SALES.BOOK_ID 
                AND DATE_FORMAT(BOOK_SALES.SALES_DATE,'%Y-%m') = '2022-01'
                #AND DATE(BOOK_SALES.SALES_DATE) BETWEEN '2022-01-01' AND '2022-01-31'
)


SELECT 
     AUTHOR_ID
    ,AUTHOR_NAME
    ,CATEGORY
    ,SUM(PRICE * SALES) AS 'TOTAL_SALES'
FROM 
    R2
GROUP BY
   AUTHOR_ID , CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
    
    
#https://coding-factory.tistory.com/445

/*
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY A.AUTHOR_ID, CATEGORY DESC
*/